# Ключ проекта из SonarCloud (Project Settings → Key)
sonar.projectKey=python-project-50

# Только для SonarCloud (название организации)
sonar.organization=lysenkovilya-hexlet

# Пути к исходникам и тестам
sonar.sources=gendiff
sonar.tests=tests

# Отчет о покрытии кода
sonar.python.coverage.reportPaths=coverage.xml

# Дополнительные настройки
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10